<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {{ get_title() }}
        {{ stylesheet_link('bootstrap/css/bootstrap.css') }}
        {{ stylesheet_link('css/style.css') }}
<!--		{{ stylesheet_link('css/nprogress.css') }}-->
		{{ stylesheet_link('theme/admin/css/styles.css') }}
		
		
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Your invoices">
        <meta name="author" content="Phalcon Team">
		
		
		{{ javascript_include('js/jquery.min.js') }}
<!--		{{ javascript_include('js/nprogress.js') }}-->
        {{ javascript_include('bootstrap/js/bootstrap.js') }}
		 {{ javascript_include('theme/admin/js/plugins/jquery/jquery-ui.min.js') }}
		
        {{ javascript_include('js/utils.js') }}
		{{ javascript_include('theme/admin/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }}
		{{ javascript_include('theme/admin/js/plugins/jquery-validation/jquery.validate.min.js') }}
		
		
		<script>
//			 $(document).ready(function(){
//				 NProgress.start();
//			 });
//			 
//			  $(window).load(function(){
//				 NProgress.done();
//			 });
		</script>
    </head>
    <body>
		  
        {{ content() }}
			
		
		  
    </body>
</html>